services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pss
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pss
    restart: unless-stopped

  ipa-service:
    build: ./ipa-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - pss

  sales-service:
    build: ./sales-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - ipa-service
    networks:
      - pss

  reporting-service:
    build: ./reporting-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - ipa-service
      - sales-service
    networks:
      - pss

  dcs-service:
    build: ./dcs-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - ipa-service
      - sales-service
    networks:
      - pss








networks:
  pss:
    driver: bridge

volumes:
  postgres:
  pgadmin:
