-- liquibase formatted sql
CREATE TABLE IF NOT EXISTS master.tenant_config (
                                                    "id" varchar NOT NULL
                                                    CONSTRAINT tenant_pk
                                                    PRIMARY KEY,
                                                    "name" varchar NOT NULL
                                                    CONSTRAINT tenant_name_uc
                                                    UNIQUE,
                                                    "schema" varchar NOT NULL
                                                    CONSTRAINT tenant_schema_uc
                                                    UNIQUE,
                                                    "issuer" varchar NOT NULL
                                                    CONSTRAINT tenant_issuer_uc
                                                    UNIQUE
);
-- changeset mdabulbasar:1691046394746-1
CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

-- changeset mdabulbasar:1691046394746-2
CREATE TABLE usba.adm_action
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    sort_order   INTEGER,
    menu_id      BIGINT,
    CONSTRAINT pk_adm_action PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-3
CREATE TABLE usba.adm_currency
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    code         VARCHAR(255),
    CONSTRAINT pk_adm_currency PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-4
CREATE TABLE usba.adm_department
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    CONSTRAINT pk_adm_department PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-5
CREATE TABLE usba.adm_designation
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    CONSTRAINT pk_adm_designation PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-6
CREATE TABLE usba.adm_email_data
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date    TIMESTAMP WITHOUT TIME ZONE,
    created_by      BIGINT,
    updated_by      BIGINT,
    updated_date    TIMESTAMP WITHOUT TIME ZONE,
    version         INTEGER                                 NOT NULL,
    subject         VARCHAR(255),
    email_type      VARCHAR(255),
    attachment_path VARCHAR(255),
    body            VARCHAR(5000),
    CONSTRAINT pk_adm_email_data PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-7
CREATE TABLE usba.adm_group
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    CONSTRAINT pk_adm_group PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-8
CREATE TABLE usba.adm_group_wise_action_mapping
(
    action_id BIGINT NOT NULL,
    group_id  BIGINT NOT NULL,
    CONSTRAINT pk_adm_group_wise_action_mapping PRIMARY KEY (action_id, group_id)
);

-- changeset mdabulbasar:1691046394746-9
CREATE TABLE usba.adm_menu
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP WITHOUT TIME ZONE,
    version       INTEGER                                 NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    screen_id     VARCHAR(255),
    url           VARCHAR(255),
    icon          VARCHAR(255),
    sort_order    INTEGER,
    sub_module_id BIGINT,
    CONSTRAINT pk_adm_menu PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-10
CREATE TABLE usba.adm_module
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    sort_order   INTEGER,
    CONSTRAINT pk_adm_module PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-11
CREATE TABLE usba.adm_otp
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otp_code     VARCHAR(6),
    otp_type     VARCHAR(255),
    expiration   TIMESTAMP WITHOUT TIME ZONE,
    resend_timer TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT,
    CONSTRAINT pk_adm_otp PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-12
CREATE TABLE usba.adm_otp_log
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otp_code        VARCHAR(6),
    otp_status      VARCHAR(255),
    otp_type        INTEGER,
    otp_status_date TIMESTAMP WITHOUT TIME ZONE,
    user_id         BIGINT,
    CONSTRAINT pk_adm_otp_log PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-13
CREATE TABLE usba.adm_password_policy
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date                TIMESTAMP WITHOUT TIME ZONE,
    created_by                  BIGINT,
    updated_by                  BIGINT,
    updated_date                TIMESTAMP WITHOUT TIME ZONE,
    version                     INTEGER                                 NOT NULL,
    password_length             INTEGER,
    contains_uppercase          BOOLEAN,
    contains_lowercase          BOOLEAN,
    contains_digit              BOOLEAN,
    contains_special_characters BOOLEAN,
    CONSTRAINT pk_adm_password_policy PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-14
CREATE TABLE usba.adm_password_reset
(
    token_id   UUID NOT NULL,
    user_id    BIGINT,
    expiration TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_adm_password_reset PRIMARY KEY (token_id)
);

-- changeset mdabulbasar:1691046394746-15
CREATE TABLE usba.adm_personal_info
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date     TIMESTAMP WITHOUT TIME ZONE,
    created_by       BIGINT,
    updated_by       BIGINT,
    updated_date     TIMESTAMP WITHOUT TIME ZONE,
    version          INTEGER                                 NOT NULL,
    first_name       VARCHAR(255),
    last_name        VARCHAR(255),
    department_id    BIGINT,
    designation_id   BIGINT,
    email_official   VARCHAR(255),
    email_other      VARCHAR(255),
    mobile_number    VARCHAR(255),
    telephone_number VARCHAR(255),
    CONSTRAINT pk_adm_personal_info PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-16
CREATE TABLE usba.adm_point_of_sale
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    CONSTRAINT pk_adm_point_of_sale PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-17
CREATE TABLE usba.adm_refresh_token
(
    token_id   UUID NOT NULL,
    user_id    BIGINT,
    expiration TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_adm_refresh_token PRIMARY KEY (token_id)
);

-- changeset mdabulbasar:1691046394746-18
CREATE TABLE usba.adm_sub_module
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    sort_order   INTEGER,
    module_id    BIGINT,
    CONSTRAINT pk_adm_sub_module PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-19
CREATE TABLE usba.adm_user
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date         TIMESTAMP WITHOUT TIME ZONE,
    created_by           BIGINT,
    updated_by           BIGINT,
    updated_date         TIMESTAMP WITHOUT TIME ZONE,
    version              INTEGER                                 NOT NULL,
    email                VARCHAR(255),
    username             VARCHAR(255),
    password             VARCHAR(255),
    company_code         VARCHAR(255),
    user_code            VARCHAR(255),
    active               BOOLEAN                                 NOT NULL,
    is2fa_enabled        BOOLEAN                                 NOT NULL,
    password_expiry_date TIMESTAMP WITHOUT TIME ZONE,
    group_id             BIGINT,
    point_of_sale_id     BIGINT,
    access_level         VARCHAR(255),
    user_type_id         BIGINT,
    personal_info_id     BIGINT,
    CONSTRAINT pk_adm_user PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-20
CREATE TABLE usba.adm_user_additional_action_permission
(
    action_id BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    CONSTRAINT pk_adm_user_additional_action_permission PRIMARY KEY (action_id, user_id)
);

-- changeset mdabulbasar:1691046394746-21
CREATE TABLE usba.adm_user_airport_mapping
(
    airport_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT pk_adm_user_airport_mapping PRIMARY KEY (airport_id, user_id)
);

-- changeset mdabulbasar:1691046394746-22
CREATE TABLE usba.adm_user_currency_mapping
(
    currency_id BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    CONSTRAINT pk_adm_user_currency_mapping PRIMARY KEY (currency_id, user_id)
);

-- changeset mdabulbasar:1691046394746-23
CREATE TABLE usba.adm_user_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_adm_user_type PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-24
CREATE TABLE inv_airport
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    CONSTRAINT pk_inv_airport PRIMARY KEY (id)
);

-- changeset mdabulbasar:1691046394746-25
ALTER TABLE usba.adm_action
    ADD CONSTRAINT uc_adm_action_name UNIQUE (name);

-- changeset mdabulbasar:1691046394746-26
ALTER TABLE usba.adm_currency
    ADD CONSTRAINT uc_adm_currency_code UNIQUE (code);

-- changeset mdabulbasar:1691046394746-27
ALTER TABLE usba.adm_department
    ADD CONSTRAINT uc_adm_department_name UNIQUE (name);

-- changeset mdabulbasar:1691046394746-28
ALTER TABLE usba.adm_designation
    ADD CONSTRAINT uc_adm_designation_name UNIQUE (name);

-- changeset mdabulbasar:1691046394746-29
ALTER TABLE usba.adm_email_data
    ADD CONSTRAINT uc_adm_email_data_emailtype UNIQUE (email_type);

-- changeset mdabulbasar:1691046394746-30
ALTER TABLE usba.adm_group
    ADD CONSTRAINT uc_adm_group_name UNIQUE (name);

-- changeset mdabulbasar:1691046394746-31
ALTER TABLE usba.adm_menu
    ADD CONSTRAINT uc_adm_menu_name UNIQUE (name);

-- changeset mdabulbasar:1691046394746-32
ALTER TABLE usba.adm_menu
    ADD CONSTRAINT uc_adm_menu_screenid UNIQUE (screen_id);

-- changeset mdabulbasar:1691046394746-33
ALTER TABLE usba.adm_menu
    ADD CONSTRAINT uc_adm_menu_url UNIQUE (url);

-- changeset mdabulbasar:1691046394746-34
ALTER TABLE usba.adm_module
    ADD CONSTRAINT uc_adm_module_name UNIQUE (name);

-- changeset mdabulbasar:1691046394746-35
ALTER TABLE usba.adm_point_of_sale
    ADD CONSTRAINT uc_adm_point_of_sale_name UNIQUE (name);

-- changeset mdabulbasar:1691046394746-36
ALTER TABLE usba.adm_user
    ADD CONSTRAINT uc_adm_user_email UNIQUE (email);

-- changeset mdabulbasar:1691046394746-37
ALTER TABLE usba.adm_user_type
    ADD CONSTRAINT uc_adm_user_type_name UNIQUE (name);

-- changeset mdabulbasar:1691046394746-38
ALTER TABLE usba.adm_user
    ADD CONSTRAINT uc_adm_user_username UNIQUE (username);

-- changeset mdabulbasar:1691046394746-39
ALTER TABLE usba.adm_action
    ADD CONSTRAINT FK_ADM_ACTION_ON_MENU FOREIGN KEY (menu_id) REFERENCES usba.adm_menu (id);

-- changeset mdabulbasar:1691046394746-40
ALTER TABLE usba.adm_menu
    ADD CONSTRAINT FK_ADM_MENU_ON_SUBMODULE FOREIGN KEY (sub_module_id) REFERENCES usba.adm_sub_module (id);

-- changeset mdabulbasar:1691046394746-41
ALTER TABLE usba.adm_otp_log
    ADD CONSTRAINT FK_ADM_OTP_LOG_ON_USER FOREIGN KEY (user_id) REFERENCES usba.adm_user (id);

-- changeset mdabulbasar:1691046394746-42
ALTER TABLE usba.adm_otp
    ADD CONSTRAINT FK_ADM_OTP_ON_USER FOREIGN KEY (user_id) REFERENCES usba.adm_user (id);

-- changeset mdabulbasar:1691046394746-43
ALTER TABLE usba.adm_password_reset
    ADD CONSTRAINT FK_ADM_PASSWORD_RESET_ON_USER FOREIGN KEY (user_id) REFERENCES usba.adm_user (id);

-- changeset mdabulbasar:1691046394746-44
ALTER TABLE usba.adm_personal_info
    ADD CONSTRAINT FK_ADM_PERSONAL_INFO_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES usba.adm_department (id);

-- changeset mdabulbasar:1691046394746-45
ALTER TABLE usba.adm_personal_info
    ADD CONSTRAINT FK_ADM_PERSONAL_INFO_ON_DESIGNATION FOREIGN KEY (designation_id) REFERENCES usba.adm_designation (id);

-- changeset mdabulbasar:1691046394746-46
ALTER TABLE usba.adm_refresh_token
    ADD CONSTRAINT FK_ADM_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES usba.adm_user (id);

-- changeset mdabulbasar:1691046394746-47
ALTER TABLE usba.adm_sub_module
    ADD CONSTRAINT FK_ADM_SUB_MODULE_ON_MODULE FOREIGN KEY (module_id) REFERENCES usba.adm_module (id);

-- changeset mdabulbasar:1691046394746-48
ALTER TABLE usba.adm_user
    ADD CONSTRAINT FK_ADM_USER_ON_GROUP FOREIGN KEY (group_id) REFERENCES usba.adm_group (id);

-- changeset mdabulbasar:1691046394746-49
ALTER TABLE usba.adm_user
    ADD CONSTRAINT FK_ADM_USER_ON_PERSONALINFO FOREIGN KEY (personal_info_id) REFERENCES usba.adm_personal_info (id);

-- changeset mdabulbasar:1691046394746-50
ALTER TABLE usba.adm_user
    ADD CONSTRAINT FK_ADM_USER_ON_POINTOFSALE FOREIGN KEY (point_of_sale_id) REFERENCES usba.adm_point_of_sale (id);

-- changeset mdabulbasar:1691046394746-51
ALTER TABLE usba.adm_user
    ADD CONSTRAINT FK_ADM_USER_ON_USERTYPE FOREIGN KEY (user_type_id) REFERENCES usba.adm_user_type (id);

-- changeset mdabulbasar:1691046394746-52
ALTER TABLE usba.adm_group_wise_action_mapping
    ADD CONSTRAINT fk_admgrowisactmap_on_action FOREIGN KEY (action_id) REFERENCES usba.adm_action (id);

-- changeset mdabulbasar:1691046394746-53
ALTER TABLE usba.adm_group_wise_action_mapping
    ADD CONSTRAINT fk_admgrowisactmap_on_group FOREIGN KEY (group_id) REFERENCES usba.adm_group (id);

-- changeset mdabulbasar:1691046394746-54
ALTER TABLE usba.adm_user_additional_action_permission
    ADD CONSTRAINT fk_admuseaddactper_on_action FOREIGN KEY (action_id) REFERENCES usba.adm_action (id);

-- changeset mdabulbasar:1691046394746-55
ALTER TABLE usba.adm_user_additional_action_permission
    ADD CONSTRAINT fk_admuseaddactper_on_user FOREIGN KEY (user_id) REFERENCES usba.adm_user (id);

-- changeset mdabulbasar:1691046394746-56
ALTER TABLE usba.adm_user_airport_mapping
    ADD CONSTRAINT fk_admuseairmap_on_airport FOREIGN KEY (airport_id) REFERENCES inv_airport (id);

-- changeset mdabulbasar:1691046394746-57
ALTER TABLE usba.adm_user_airport_mapping
    ADD CONSTRAINT fk_admuseairmap_on_user FOREIGN KEY (user_id) REFERENCES usba.adm_user (id);

-- changeset mdabulbasar:1691046394746-58
ALTER TABLE usba.adm_user_currency_mapping
    ADD CONSTRAINT fk_admusecurmap_on_currency FOREIGN KEY (currency_id) REFERENCES usba.adm_currency (id);

-- changeset mdabulbasar:1691046394746-59
ALTER TABLE usba.adm_user_currency_mapping
    ADD CONSTRAINT fk_admusecurmap_on_user FOREIGN KEY (user_id) REFERENCES usba.adm_user (id);

