spring:
  application:
    name: pss-pricing
  datasource:
    url: jdbc:postgresql://localhost:5432/pss
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 7001
      hashkey: pss2023Technonext

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8080


useExpiringMapToBlackListAccessToken: false

