spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pss
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 7001
      hashkey: pss2023Technonext

server:
  port: 8080

useExpiringMapToBlackListAccessToken: false

