spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pss
    username: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 7001
      hashkey: pss2023Technonext

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    url: /v3/api-docs

server:
  port: 8080
  servlet:
    context-path: /pss/pricing
useExpiringMapToBlackListAccessToken: false

