ALTER TABLE adm_user
    ADD IF NOT EXISTS user_type_id BIGINT;

ALTER TABLE adm_user
    ADD IF NOT EXISTS point_of_sale_id BIGINT;

ALTER TABLE adm_user
    ADD IF NOT EXISTS access_level VARCHAR(9);

CREATE TABLE IF NOT EXISTS adm_user_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(30) UNIQUE,
    description VARCHAR(255),
    CONSTRAINT pk_adm_user_type PRIMARY KEY (id)
);

INSERT INTO adm_user_type
VALUES (1, 'BACK_OFFICE', 'Back office user'),
       (2, 'CORPORATE', 'Corporate user'),
       (3, 'AGENT', 'Agent user')
ON CONFLICT DO NOTHING;


CREATE TABLE inv_airport
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255) UNIQUE                     NOT NULL,
    CONSTRAINT pK_inv_airport PRIMARY KEY (id)
);

INSERT INTO inv_airport(id, name, version)
VALUES (1, 'Dhaka', 0),
       (2, 'Kolkata', 0),
       (3, 'Qatar', 0);

CREATE TABLE adm_user_airport_mapping
(
    user_id    BIGINT,
    airport_id BIGINT
);

CREATE TABLE adm_user_currency_mapping
(
    user_id     BIGINT,
    currency_id BIGINT
);


INSERT INTO adm_user_airport_mapping
VALUES (1, 2),
       (1, 3);


INSERT INTO adm_user_currency_mapping
VALUES (1, 1),
       (1, 3);

insert into adm_currency(id, name, code, version)
values (1, 'US Dollar', 'USD', 0),
       (2, 'Euro', 'euro', 0),
       (3, 'Taka', 'BDT', 0),
       (4, 'India Rupee', 'INR', 0)
on conflict do nothing;

-- Create Point of Sale Table
insert into adm_point_of_sale(id, name, version)
values (1, 'Dhaka', 0),
       (2, 'Chittagong', 0),
       (3, 'Delhi', 0),
       (4, 'Doha', 0),
       (5, 'NewYork', 0)
on conflict do nothing;

-- initialize airport tablle

insert into inv_airport(id, name, version)
values (1, 'Dhaka', 0),
       (2, 'Chittagong', 0),
       (3, 'Qatar', 0),
       (4, 'Kolkata', 0)
on conflict do nothing;

UPDATE adm_user
set user_type_id =1
WHERE id = 1;

UPDATE adm_user
SET point_of_sale_id = 1
WHERE id = 1;

UPDATE adm_user
SET access_level = 'APPROVER'
WHERE id = 1;

UPDATE adm_user
SET user_code = 'adm'
WHERE id = 1;