package com.usb.pss.ipaservice.admin.model.enums;

public enum ServiceName {
    INVENTORY, PRICING, SALES, DCS, ADMIN,
    INVENTORY_BASE_PARAMETER, INVENTORY_FLIGHT_MANAGEMENT, PRICING_CLASSES_MANAGEMENT,
    PRICING_FARE_MANAGEMENT, SALES_CUSTOMER, SALES_BOOKING
}
