package com.usb.pss.ipaservice.admin.model.enums;

public enum ServiceName {
    INVENTORY, PRICING, SALES, DCS, REPORT, ADMIN,
    INVENTORY_BASE_PARAMETER, INVENTORY_FLIGHT_MANAGEMENT, INVENTORY_GDS,
    PRICING_CLASS_MANAGEMENT, PRICING_FARE_MANAGEMENT, PRICING_TAX_AND_PENALTY, PRICING_OTHER_SETTING,
    SALES_BOOKING, SALES_SEARCH, SALES_CUSTOMER, SALES_AGENCY_AND_CORPORATE, SALES_CASHBOX_MANAGEMENT,
    DCS_DEFAULT,
    REPORT_SALES, REPORT_GDS_AND_INTERLINE_SALES, REPORT_TA_AND_CORPORATE_CUSTOMER, REPORT_CENTER,
    ADMIN_ACCOUNT_SETTING, ADMIN_SECURITY_AND_ACCESS_RIGHT, ADMIN_QUEUE_MANAGEMENT, ADMIN_ONLINE_HELP
}
