CREATE TABLE IF NOT EXISTS usba.adm_access_level
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_adm_access_level PRIMARY KEY (id)
);

INSERT INTO usba.adm_access_level
VALUES (1, 'APPROVER'),
       (2, 'REVIEWER')
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS usba.adm_user_access_level_mapping
(
    access_level_id BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    CONSTRAINT pk_adm_user_access_level_mapping PRIMARY KEY (access_level_id, user_id)
);

INSERT INTO usba.adm_user_access_level_mapping
VALUES (1, 1),
       (2, 1)
ON CONFLICT DO NOTHING;

INSERT INTO usba.adm_user_type
VALUES (1, 'BACK_OFFICE', 'Back office user'),
       (2, 'CORPORATE', 'Corporate user'),
       (3, 'AGENT', 'Agent user')
ON CONFLICT DO NOTHING;

INSERT INTO inv_airport(id, name, version)
VALUES (1, 'Dhaka', 0),
       (2, 'Kolkata', 0),
       (3, 'Qatar', 0)
ON CONFLICT DO NOTHING;

insert into usba.adm_currency(id, name, code, version)
values (1, 'US Dollar', 'USD', 0),
       (2, 'Euro', 'euro', 0),
       (3, 'Taka', 'BDT', 0),
       (4, 'India Rupee', 'INR', 0)
on conflict do nothing;

-- Create Point of Sale Table
insert into usba.adm_point_of_sale(id, name, version)
values (1, 'Dhaka', 0),
       (2, 'Chittagong', 0),
       (3, 'Delhi', 0),
       (4, 'Doha', 0),
       (5, 'NewYork', 0)
on conflict do nothing;

-- initialize airport tablle

insert into usba.inv_airport(id, name, version)
values (1, 'Dhaka', 0),
       (2, 'Chittagong', 0),
       (3, 'Qatar', 0),
       (4, 'Kolkata', 0)
on conflict do nothing;

INSERT INTO usba.adm_user_airport_mapping(user_id, airport_id)
VALUES (1, 2),
       (1, 3)
ON CONFLICT DO NOTHING;


INSERT INTO usba.adm_user_currency_mapping(user_id, currency_id)
VALUES (1, 1),
       (1, 3)
ON CONFLICT DO NOTHING;

UPDATE usba.adm_user
set user_type_id =1
WHERE id = 1;

UPDATE usba.adm_user
set point_of_sale_id = 2
WHERE id = 1;


UPDATE usba.adm_user
SET user_code = 'adm'
WHERE id = 1;