-- Authored by Junaid Khan Pathan

CREATE TABLE IF NOT EXISTS usba.adm_job_config
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    job_name                VARCHAR(64),
    job_type                VARCHAR(32) UNIQUE NOT NULL,
    job_description         VARCHAR(512),
    cron_expression         VARCHAR(64),
    job_message_email       VARCHAR(64),
    is_enabled              BOOLEAN,
    is_triggered            BOOLEAN,
    is_scheduled            BOOLEAN,
    has_job_endingMessage   BOOLEAN,
    fixed_rate              INTEGER,
    fixed_delay             INTEGER,
    CONSTRAINT pk_adm_job_config PRIMARY KEY (id)
);