-- changeset ablonewolf-293-1
CREATE TABLE adm_personal_info
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date     TIMESTAMP WITHOUT TIME ZONE,
    created_by       BIGINT,
    updated_by       BIGINT,
    updated_date     TIMESTAMP WITHOUT TIME ZONE,
    version          INTEGER                                 NOT NULL,
    first_name       VARCHAR(255),
    last_name        VARCHAR(255),
    department_id    BIGINT,
    designation_id   BIGINT,
    email_official   VARCHAR(255),
    email_other      VARCHAR(255),
    mobile_number    VARCHAR(255),
    telephone_number VARCHAR(255),
    access_level     VARCHAR(255),
    airport          VARCHAR(255),
    CONSTRAINT pk_adm_personal_info PRIMARY KEY (id)
);

-- changeset ablonewolf:293-2
CREATE TABLE adm_user
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date     TIMESTAMP WITHOUT TIME ZONE,
    created_by       BIGINT,
    updated_by       BIGINT,
    updated_date     TIMESTAMP WITHOUT TIME ZONE,
    version          INTEGER                                 NOT NULL,
    email            VARCHAR(255),
    is2fa_enabled    BOOLEAN                                 NOT NULL,
    username         VARCHAR(255),
    password         VARCHAR(255),
    user_type        VARCHAR(255)                            NOT NULL,
    user_code        VARCHAR(255)                            NOT NULL,
    company_code     VARCHAR(255),
    active           BOOLEAN                                 NOT NULL,
    group_id         BIGINT,
    personal_info_id BIGINT,
    CONSTRAINT pk_adm_user PRIMARY KEY (id)
);