-- liquibase formatted sql

-- changeset ablonewolf:202203-1
CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

-- changeset ablonewolf:202203-2
CREATE TABLE adm_action
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    sort_order   INTEGER,
    menu_id      BIGINT,
    CONSTRAINT pk_adm_action PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-3
CREATE TABLE adm_currency
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    code         VARCHAR(255),
    CONSTRAINT pk_adm_currency PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-4
CREATE TABLE adm_department
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    CONSTRAINT pk_adm_department PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-5
CREATE TABLE adm_designation
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    CONSTRAINT pk_adm_designation PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-6
CREATE TABLE adm_group
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    CONSTRAINT pk_adm_group PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-7
CREATE TABLE adm_group_wise_action_mapping
(
    action_id BIGINT NOT NULL,
    group_id  BIGINT NOT NULL,
    CONSTRAINT pk_adm_group_wise_action_mapping PRIMARY KEY (action_id, group_id)
);

-- changeset ablonewolf:202203-8
CREATE TABLE adm_menu
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP WITHOUT TIME ZONE,
    version       INTEGER                                 NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    screen_id     VARCHAR(255),
    url           VARCHAR(255),
    icon          VARCHAR(255),
    sort_order    INTEGER,
    sub_module_id BIGINT,
    CONSTRAINT pk_adm_menu PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-9
CREATE TABLE adm_module
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    sort_order   INTEGER,
    CONSTRAINT pk_adm_module PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-10
CREATE TABLE adm_password_policy
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date                TIMESTAMP WITHOUT TIME ZONE,
    created_by                  BIGINT,
    updated_by                  BIGINT,
    updated_date                TIMESTAMP WITHOUT TIME ZONE,
    version                     INTEGER                                 NOT NULL,
    password_length             INTEGER,
    contains_uppercase          BOOLEAN,
    contains_lowercase          BOOLEAN,
    contains_digit              BOOLEAN,
    contains_special_characters BOOLEAN,
    CONSTRAINT pk_adm_password_policy PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-11
CREATE TABLE adm_password_reset
(
    token_id   UUID NOT NULL,
    user_id    BIGINT,
    expiration TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_adm_password_reset PRIMARY KEY (token_id)
);

-- changeset ablonewolf:202203-12
CREATE TABLE adm_personal_info
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date     TIMESTAMP WITHOUT TIME ZONE,
    created_by       BIGINT,
    updated_by       BIGINT,
    updated_date     TIMESTAMP WITHOUT TIME ZONE,
    version          INTEGER                                 NOT NULL,
    first_name       VARCHAR(255),
    last_name        VARCHAR(255),
    department_id    BIGINT,
    designation_id   BIGINT,
    email_official   VARCHAR(255),
    email_other      VARCHAR(255),
    mobile_number    VARCHAR(255),
    telephone_number VARCHAR(255),
    access_level     VARCHAR(255),
    airport          VARCHAR(255),
    CONSTRAINT pk_adm_personal_info PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-13
CREATE TABLE adm_personal_info_currency_mapping
(
    currency_id      BIGINT NOT NULL,
    personal_info_id BIGINT NOT NULL,
    CONSTRAINT pk_adm_personal_info_currency_mapping PRIMARY KEY (currency_id, personal_info_id)
);

-- changeset ablonewolf:202203-14
CREATE TABLE adm_personal_info_point_of_sale_mapping
(
    personal_info_id BIGINT NOT NULL,
    point_of_sale_id BIGINT NOT NULL,
    CONSTRAINT pk_adm_personal_info_point_of_sale_mapping PRIMARY KEY (personal_info_id, point_of_sale_id)
);

-- changeset ablonewolf:202203-15
CREATE TABLE adm_point_of_sale
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    CONSTRAINT pk_adm_point_of_sale PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-16
CREATE TABLE adm_refresh_token
(
    token_id   UUID NOT NULL,
    user_id    BIGINT,
    expiration TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_adm_refresh_token PRIMARY KEY (token_id)
);

-- changeset ablonewolf:202203-17
CREATE TABLE adm_sub_module
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    sort_order   INTEGER,
    module_id    BIGINT,
    CONSTRAINT pk_adm_sub_module PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-18
CREATE TABLE adm_user
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date     TIMESTAMP WITHOUT TIME ZONE,
    created_by       BIGINT,
    updated_by       BIGINT,
    updated_date     TIMESTAMP WITHOUT TIME ZONE,
    version          INTEGER                                 NOT NULL,
    email            VARCHAR(255),
    is2fa_enabled    BOOLEAN                                 NOT NULL,
    username         VARCHAR(255),
    password         VARCHAR(255),
    user_type        VARCHAR(255)                            NOT NULL,
    user_code        VARCHAR(255)                            NOT NULL,
    company_code     VARCHAR(255),
    active           BOOLEAN                                 NOT NULL,
    group_id         BIGINT,
    personal_info_id BIGINT,
    CONSTRAINT pk_adm_user PRIMARY KEY (id)
);

-- changeset ablonewolf:202203-19
CREATE TABLE adm_user_additional_action_permission
(
    action_id BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    CONSTRAINT pk_adm_user_additional_action_permission PRIMARY KEY (action_id, user_id)
);

-- changeset ablonewolf:202203-20
ALTER TABLE adm_action
    ADD CONSTRAINT uc_adm_action_name UNIQUE (name);

-- changeset ablonewolf:202203-21
ALTER TABLE adm_currency
    ADD CONSTRAINT uc_adm_currency_code UNIQUE (code);

-- changeset ablonewolf:202203-22
ALTER TABLE adm_department
    ADD CONSTRAINT uc_adm_department_name UNIQUE (name);

-- changeset ablonewolf:202203-23
ALTER TABLE adm_designation
    ADD CONSTRAINT uc_adm_designation_name UNIQUE (name);

-- changeset ablonewolf:202203-24
ALTER TABLE adm_group
    ADD CONSTRAINT uc_adm_group_name UNIQUE (name);

-- changeset ablonewolf:202203-25
ALTER TABLE adm_menu
    ADD CONSTRAINT uc_adm_menu_name UNIQUE (name);

-- changeset ablonewolf:202203-26
ALTER TABLE adm_menu
    ADD CONSTRAINT uc_adm_menu_screenid UNIQUE (screen_id);

-- changeset ablonewolf:202203-27
ALTER TABLE adm_menu
    ADD CONSTRAINT uc_adm_menu_url UNIQUE (url);

-- changeset ablonewolf:202203-28
ALTER TABLE adm_module
    ADD CONSTRAINT uc_adm_module_name UNIQUE (name);

-- changeset ablonewolf:202203-29
ALTER TABLE adm_point_of_sale
    ADD CONSTRAINT uc_adm_point_of_sale_name UNIQUE (name);

-- changeset ablonewolf:202203-30
ALTER TABLE adm_user
    ADD CONSTRAINT uc_adm_user_email UNIQUE (email);

-- changeset ablonewolf:202203-31
ALTER TABLE adm_user
    ADD CONSTRAINT uc_adm_user_username UNIQUE (username);

-- changeset ablonewolf:202203-32
ALTER TABLE adm_action
    ADD CONSTRAINT FK_ADM_ACTION_ON_MENU FOREIGN KEY (menu_id) REFERENCES adm_menu (id);

-- changeset ablonewolf:202203-33
ALTER TABLE adm_menu
    ADD CONSTRAINT FK_ADM_MENU_ON_SUBMODULE FOREIGN KEY (sub_module_id) REFERENCES adm_sub_module (id);

-- changeset ablonewolf:202203-34
ALTER TABLE adm_password_reset
    ADD CONSTRAINT FK_ADM_PASSWORD_RESET_ON_USER FOREIGN KEY (user_id) REFERENCES adm_user (id);

-- changeset ablonewolf:202203-35
ALTER TABLE adm_personal_info
    ADD CONSTRAINT FK_ADM_PERSONAL_INFO_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES adm_department (id);

-- changeset ablonewolf:202203-36
ALTER TABLE adm_personal_info
    ADD CONSTRAINT FK_ADM_PERSONAL_INFO_ON_DESIGNATION FOREIGN KEY (designation_id) REFERENCES adm_designation (id);

-- changeset ablonewolf:202203-37
ALTER TABLE adm_refresh_token
    ADD CONSTRAINT FK_ADM_REFRESH_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES adm_user (id);

-- changeset ablonewolf:202203-38
ALTER TABLE adm_sub_module
    ADD CONSTRAINT FK_ADM_SUB_MODULE_ON_MODULE FOREIGN KEY (module_id) REFERENCES adm_module (id);

-- changeset ablonewolf:202203-39
ALTER TABLE adm_user
    ADD CONSTRAINT FK_ADM_USER_ON_GROUP FOREIGN KEY (group_id) REFERENCES adm_group (id);

-- changeset ablonewolf:202203-40
ALTER TABLE adm_user
    ADD CONSTRAINT FK_ADM_USER_ON_PERSONALINFO FOREIGN KEY (personal_info_id) REFERENCES adm_personal_info (id);

-- changeset ablonewolf:202203-41
ALTER TABLE adm_group_wise_action_mapping
    ADD CONSTRAINT fk_admgrowisactmap_on_action FOREIGN KEY (action_id) REFERENCES adm_action (id);

-- changeset ablonewolf:202203-42
ALTER TABLE adm_group_wise_action_mapping
    ADD CONSTRAINT fk_admgrowisactmap_on_group FOREIGN KEY (group_id) REFERENCES adm_group (id);

-- changeset ablonewolf:202203-43
ALTER TABLE adm_personal_info_currency_mapping
    ADD CONSTRAINT fk_admperinfcurmap_on_currency FOREIGN KEY (currency_id) REFERENCES adm_currency (id);

-- changeset ablonewolf:202203-44
ALTER TABLE adm_personal_info_currency_mapping
    ADD CONSTRAINT fk_admperinfcurmap_on_personal_info FOREIGN KEY (personal_info_id) REFERENCES adm_personal_info (id);

-- changeset ablonewolf:202203-45
ALTER TABLE adm_personal_info_point_of_sale_mapping
    ADD CONSTRAINT fk_admperinfpoiofsalmap_on_personal_info FOREIGN KEY (personal_info_id) REFERENCES adm_personal_info (id);

-- changeset ablonewolf:202203-46
ALTER TABLE adm_personal_info_point_of_sale_mapping
    ADD CONSTRAINT fk_admperinfpoiofsalmap_on_point_of_sale FOREIGN KEY (point_of_sale_id) REFERENCES adm_point_of_sale (id);

-- changeset ablonewolf:202203-47
ALTER TABLE adm_user_additional_action_permission
    ADD CONSTRAINT fk_admuseaddactper_on_action FOREIGN KEY (action_id) REFERENCES adm_action (id);

-- changeset ablonewolf:202203-48
ALTER TABLE adm_user_additional_action_permission
    ADD CONSTRAINT fk_admuseaddactper_on_user FOREIGN KEY (user_id) REFERENCES adm_user (id);

