-- ablonewolf-293-1

ALTER TABLE adm_user
    ADD COLUMN
        if not exists is2fa_enabled BOOLEAN;

ALTER TABLE adm_user
    ADD COLUMN
        IF NOT EXISTS user_code VARCHAR(6);


CREATE TABLE IF NOT EXISTS adm_user_currency_mapping
(
    user_id     BIGINT NOT NULL,
    currency_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS adm_user_airport_mapping
(
    user_id    BIGINT NOT NULL,
    airport_id BIGINT NOT NULL
);

CREATE TABLE inv_airport
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP WITHOUT TIME ZONE,
    version      INTEGER                                 NOT NULL,
    name         VARCHAR(255) UNIQUE                     NOT NULL,
    CONSTRAINT pK_inv_airport PRIMARY KEY (id)
);


ALTER TABLE adm_user
    ADD COLUMN
        IF NOT EXISTS point_of_sale_id BIGINT NOT NULL;



update adm_user
set is2fa_enabled = false
where id = 1;

update adm_user
set user_code = 'adm11'
where id = 1;

update adm_user
set access_level = 1
where id = 1;

update adm_user
set is2fa_enabled = false
where id = 1;

