-- liquibase formatted sql

-- changeset kpjunaid:1690715096662-1
CREATE TABLE adm_email_data
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date    TIMESTAMP WITHOUT TIME ZONE,
    created_by      BIGINT,
    updated_by      BIGINT,
    updated_date    TIMESTAMP WITHOUT TIME ZONE,
    version         INTEGER                                 NOT NULL,
    subject         VARCHAR(255),
    email_type      INTEGER,
    attachment_path VARCHAR(255),
    body            VARCHAR(5000),
    CONSTRAINT pk_adm_email_data PRIMARY KEY (id)
);

-- changeset kpjunaid:1690715096662-2
CREATE TABLE adm_otp
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otp_code   VARCHAR(255),
    expiration TIMESTAMP WITHOUT TIME ZONE,
    otp_type   INTEGER,
    otp_status INTEGER,
    user_id    BIGINT,
    CONSTRAINT pk_adm_otp PRIMARY KEY (id)
);

-- changeset kpjunaid:1690715096662-3
CREATE TABLE adm_otp_log
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otp_code        VARCHAR(255),
    otp_status      INTEGER,
    otp_type        INTEGER,
    otp_status_date TIMESTAMP WITHOUT TIME ZONE,
    user_id         BIGINT,
    CONSTRAINT pk_adm_otp_log PRIMARY KEY (id)
);

-- changeset kpjunaid:1690715096662-4
ALTER TABLE adm_user
    ADD is2fa_enabled BOOLEAN;

-- changeset kpjunaid:1690715096662-5
ALTER TABLE adm_user
    ALTER COLUMN is2fa_enabled SET NOT NULL;

-- changeset kpjunaid:1690715096662-6
ALTER TABLE adm_otp_log
    ADD CONSTRAINT FK_ADM_OTP_LOG_ON_USER FOREIGN KEY (user_id) REFERENCES adm_user (id);

-- changeset kpjunaid:1690715096662-7
ALTER TABLE adm_otp
    ADD CONSTRAINT FK_ADM_OTP_ON_USER FOREIGN KEY (user_id) REFERENCES adm_user (id);

