-- Authored by Junaid Khan Pathan

CREATE TABLE usba.adm_email_data
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date    TIMESTAMP WITHOUT TIME ZONE,
    created_by      BIGINT,
    updated_by      BIGINT,
    updated_date    TIMESTAMP WITHOUT TIME ZONE,
    version         INTEGER                                 NOT NULL,
    subject         VARCHAR(255),
    email_type      INTEGER,
    attachment_path VARCHAR(255),
    body            VARCHAR(5000),
    CONSTRAINT pk_adm_email_data PRIMARY KEY (id)
);

CREATE TABLE usba.adm_otp
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otp_code        VARCHAR(6),
    expiration      TIMESTAMP WITHOUT TIME ZONE,
    resend_timer    TIMESTAMP WITHOUT TIME ZONE,
    otp_type        INTEGER,
    user_id         BIGINT NOT NULL,
    CONSTRAINT pk_adm_otp PRIMARY KEY (id)
);

CREATE TABLE usba.adm_otp_log
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otp_code        VARCHAR(6),
    otp_status      INTEGER,
    otp_type        INTEGER,
    otp_status_date TIMESTAMP WITHOUT TIME ZONE,
    user_id         BIGINT NOT NULL,
    CONSTRAINT pk_adm_otp_log PRIMARY KEY (id)
);

ALTER TABLE usba.adm_user
    ADD IF NOT EXISTS is2fa_enabled BOOLEAN;

ALTER TABLE usba.adm_user
    ALTER COLUMN is2fa_enabled SET NOT NULL;

ALTER TABLE usba.adm_otp
    ADD CONSTRAINT FK_ADM_OTP_ON_USER FOREIGN KEY (user_id) REFERENCES usba.adm_user (id);

ALTER TABLE usba.adm_otp_log
    ADD CONSTRAINT FK_ADM_OTP_LOG_ON_USER FOREIGN KEY (user_id) REFERENCES usba.adm_user (id);