spring:
  datasource:
    url: jdbc:postgresql://###:5432/###
    username: ###
    password: ###
  data:
    redis:
      host: ###
      port: 7001
      hashkey: ###

  jpa:
    show-sql: false

application:
  security:
    jwt:
      secret-key: ###
      expiration: ###
      refresh-token:
        expiration: ###
server:
  port: ###
  servlet:
    context-path: /pss/sales

useExpiringMapToBlackListAccessToken: false
